import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/ui/Navbar";

export const metadata: Metadata = {
  title: "OH",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased min-h-screen flex flex-col`}>
        <main className="flex-1">
          <Navbar />
          {children}
        </main>
      </body>
    </html>
  );
}
