import type { Metadata } from "next";
import Navbar from "./components/layout/Navbar";
import "./globals.css";

export const metadata: Metadata = {
  title: "OH",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased min-h-screen flex flex-col`}>
        <Navbar />
        <main className="flex-1">{children}</main>
      </body>
    </html>
  );
}
